# Generated by Django 6.0.4 on 2026-05-25 16:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-award', help_text='Font Awesome class, e.g. "fas fa-fire"', max_length=50)),
                ('icon_color', models.CharField(default='#fd7e14', max_length=20)),
                ('criteria_type', models.CharField(choices=[('streak_7', '7-Day Streak'), ('streak_30', '30-Day Streak'), ('streak_100', '100-Day Streak'), ('course_complete', 'Course Completed'), ('top3_leaderboard', 'Top 3 on Leaderboard'), ('module_master', 'Module Master (10 materials)'), ('first_submit', 'First Assignment Submitted'), ('xp_500', '500 XP Milestone'), ('xp_1000', '1 000 XP Milestone'), ('xp_5000', '5 000 XP Milestone'), ('challenge_10', '10 Challenges Completed'), ('custom', 'Custom / Manual')], default='custom', max_length=30)),
                ('xp_reward', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('complete_materials', 'Complete N Materials'), ('submit_assignments', 'Submit N Assignments'), ('active_minutes', 'Be Active for N Minutes'), ('earn_xp', 'Earn N XP Today'), ('custom', 'Custom Task')], default='complete_materials', max_length=30)),
                ('target_count', models.PositiveSmallIntegerField(default=3)),
                ('xp_reward', models.PositiveSmallIntegerField(default=100)),
                ('reward_type', models.CharField(choices=[('xp', 'XP Only'), ('freeze', 'Streak Freeze'), ('badge', 'Badge'), ('xp_freeze', 'XP + Streak Freeze')], default='xp', max_length=20)),
                ('is_auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_rewards', to='leaderboard.badge')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Challenge',
                'verbose_name_plural': 'Daily Challenges',
                'ordering': ['-date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('freeze_count', models.PositiveSmallIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('tasks_today', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gamification Profile',
                'verbose_name_plural': 'Gamification Profiles',
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_amount', models.SmallIntegerField()),
                ('reason', models.CharField(choices=[('material_complete', 'Material Completed'), ('assignment_submit', 'Assignment Submitted'), ('grade_bonus', 'High-Grade Bonus'), ('challenge_complete', 'Challenge Completed'), ('badge_earned', 'Badge Earned'), ('admin_grant', 'Admin Manual Grant')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'XP Transaction',
                'verbose_name_plural': 'XP Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_ping', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Session',
                'verbose_name_plural': 'Activity Sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'session_date'], name='leaderboard_user_id_bcd2b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_completions', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='leaderboard.dailychallenge')),
            ],
            options={
                'verbose_name': 'Challenge Completion',
                'verbose_name_plural': 'Challenge Completions',
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='leaderboard.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Badge',
                'verbose_name_plural': 'User Badges',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
