# Generated by Django 6.0.4 on 2026-05-31 10:50

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='xptransaction',
            name='material_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(default='fas fa-award', help_text='Font Awesome class, e.g. "fas fa-fire"', max_length=50, validators=[django.core.validators.RegexValidator(message='Icon must be a valid Font Awesome class like "fas fa-award".', regex='^fa[srb]? fa-[a-z0-9\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon_color',
            field=models.CharField(default='#fd7e14', max_length=20, validators=[django.core.validators.RegexValidator(message='Icon color must be a 6-digit hex code, e.g. #fd7e14.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterUniqueTogether(
            name='xptransaction',
            unique_together={('user', 'reason', 'material_id')},
        ),
    ]
