# Generated by Django 6.0.4 on 2026-05-11 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, default=list, help_text='List of learning outcomes'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, default=list, help_text="List of requirements, e.g., ['Basic computer literacy', 'Internet access']"),
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('company_website', models.URLField(blank=True)),
                ('partnership_type', models.CharField(choices=[('financial_support', 'Financial Support'), ('in_kind_donations', 'In-Kind Donations'), ('volunteer_program', 'Volunteer Program'), ('corporate_sponsorship', 'Corporate Sponsorship')], help_text='Type of partnership', max_length=100)),
                ('interested_in', models.CharField(blank=True, choices=[('education', 'Education'), ('technology_access', 'Technology Access'), ('youth_empowerment', 'Youth Empowerment'), ('community_development', 'Community Development')], help_text='Areas of interest for partnership', max_length=200)),
                ('about_proposal', models.TextField(blank=True, help_text='Why the organization wants to partner with PrimeTech Foundation')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partnership Application',
                'verbose_name_plural': 'Partnership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
