# Generated by Django 6.0.4 on 2026-05-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_course_outcomes_alter_course_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='outcomes',
            field=models.TextField(blank=True, help_text='What students will learn. Use bullet points or a numbered list.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(blank=True, help_text='Course entry requirements. Use bullet points or a numbered list.'),
        ),
    ]
