# Generated by Django 6.0.4 on 2026-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_course_outcomes_alter_course_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high-school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], help_text='Highest education level attained', max_length=30),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('student', 'Student'), ('unemployed', 'Unemployed'), ('other', 'Other')], help_text='Applicant employment status', max_length=20),
        ),
    ]
