# Generated by Django 6.0.4 on 2026-05-17 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('website', '0003_alter_course_outcomes_alter_course_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='content',
            field=models.TextField(blank=True, help_text="Rich HTML content (CKEditor). Used when material_type is 'text'."),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='url',
            field=models.URLField(blank=True, help_text='YouTube / Vimeo embed URL or external resource link.'),
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_intro', models.TextField(blank=True, help_text='HTML. A personal welcome / bio from the instructor.')),
                ('learning_outcomes', models.TextField(blank=True, help_text='HTML. What students will be able to do after completing this course.')),
                ('course_relevance', models.TextField(blank=True, help_text='HTML. Why this course matters — industry context, career paths, etc.')),
                ('course_activities', models.TextField(blank=True, help_text='HTML. Types of activities: readings, quizzes, projects, live sessions, etc.')),
                ('modules_overview', models.TextField(blank=True, help_text='HTML. Week-by-week or module-by-module breakdown.')),
                ('final_project', models.TextField(blank=True, help_text='HTML. Description of the capstone / final project requirements.')),
                ('certification_info', models.TextField(blank=True, help_text='HTML. What certificate/credential students earn and how.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='website.course')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_syllabi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Syllabus',
                'verbose_name_plural': 'Course Syllabi',
            },
        ),
    ]
