# Generated by Django 6.0.4 on 2026-05-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursematerial_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('text', 'Notes'), ('video', 'Video (Embed URL)'), ('pdf', 'PDF Document'), ('file', 'File Download'), ('link', 'External Link')], default='text', max_length=20),
        ),
    ]
