# Generated by Django 6.0.4 on 2026-06-06 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursematerial_material_type'),
        ('website', '0005_newslettersubscriber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('text', 'Notes'), ('video', 'Video (YouTube/Vimeo)'), ('pdf', 'PDF Document'), ('file', 'File Download'), ('link', 'External Link')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Module heading, e.g. 'Module 1: Introduction'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short description displayed on the module card.')),
                ('notes', models.TextField(blank=True, help_text='Rich HTML notes for this module (CKEditor). Written and edited by the instructor.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the course.')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='website.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Module',
                'verbose_name_plural': 'Course Modules',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Assign to a module, or leave blank for a flat (top-level) material.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.coursemodule'),
        ),
    ]
